# Generated by Django 5.0.6 on 2024-06-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
